### PR TITLE
Removes unnecessary addition of ftrim command to flight.js file.

### PR DESCRIPTION
**Pull request by michaelshmitty**
The ftrim command is a straight proxy to the underlying ardrone connection and therefore doesn't need to be in here. Adding it to commands.js is sufficient.

Signed-off-by: Michael Smith <m@michaelsmith.be>

### CODE REVIEW

**Comment by deadprogram** [comment]
@stewart do we need to include this to generate docs correctly?

**Comment by michaelshmitty** [comment]
@deadprogram Ah maybe, I did not consider that. Let's see what @stewart says, feel free to kill this PR if necessary.

**Comment by stewart** [comment]
Currently, it is necessary due to the docs structuring. In the future this may change, but for now it needs to be in the driver file as well as the commands definition.

**Comment by deadprogram** [comment]
OK got it. In which case, closing.

**Pull request closed without merging**
